channel_fetcher:
  class: ChannelItemsFetcherJob
  schedule: "10,59 * * * *"

channel_interval_adjustment:
  class: ChannelIntervalAdjustmentJob
  schedule: every day at 3am

channel_schedule_adjustment:
  class: ChannelScheduleAdjustmentJob
  schedule: every day at 4am

solid_queue_cleanup:
  class: SolidQueueCleanupJob
  schedule: every day at 4:30am

daily_active_users_notifier:
  class: DailyActiveUsersNotifierJob
  schedule: every day at 0:05am
