channel_fetcher:
  class: ChannelItemsFetcherJob
  schedule: "10,59 * * * *"

notification_webhook_dispatcher:
  class: NotificationWebhookDispatcherJob
  schedule: "0 * * * *"

notification_email_dispatcher:
  class: NotificationEmailDispatcherJob
  schedule: "0 * * * *"

channel_group_webhook_dispatcher:
  class: ChannelGroupWebhookDispatcherJob
  schedule: "20 * * * *"

solid_queue_cleanup:
  class: SolidQueueCleanupJob
  schedule: "30 4 * * *"

daily_active_users_notifier:
  class: DailyActiveUsersNotifierJob
  schedule: "5 0 * * *"
